// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    facilities_by_state: {
        name: "facilities_by_state";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          state: string;
          /** @sqlType BIGINT */
          facility_count: number;
        }>;
      };
    facilities_by_type: {
        name: "facilities_by_type";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          facility_type: string;
          /** @sqlType BIGINT */
          facility_count: number;
        }>;
      };
    facility_summary: {
        name: "facility_summary";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          total_facilities: number;
          /** @sqlType BIGINT */
          states_covered: number;
          /** @sqlType BIGINT */
          facility_types: number;
        }>;
      };
    hello_world: {
        name: "hello_world";
        parameters: {
          /** STRING - use sql.string() */
          message: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          value: string;
        }>;
      };
    mocked_sales: {
        name: "mocked_sales";
        parameters: {
          /** INT - use sql.int() */
          max_month_num: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          month: string;
          /** @sqlType INT */
          month_num: number;
          /** @sqlType INT */
          revenue: number;
          /** @sqlType INT */
          expenses: number;
          /** @sqlType INT */
          customers: number;
        }>;
      };
  }
}
