// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    district_options: {
        name: "district_options";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          district_key: string;
          /** @sqlType STRING */
          district_name: string;
          /** @sqlType STRING */
          state_ut: string;
        }>;
      };
    dq_gap_summary: {
        name: "dq_gap_summary";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          gap_type: string;
          /** @sqlType STRING */
          severity: string;
          /** @sqlType BIGINT */
          open_gap_count: number;
        }>;
      };
    dq_gaps_open: {
        name: "dq_gaps_open";
        parameters: {
          /** STRING - use sql.string() */
          _refresh: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          gap_id: string;
          /** @sqlType STRING */
          gap_type: string;
          /** @sqlType STRING */
          severity: string;
          /** @sqlType STRING */
          entity_type: string;
          /** @sqlType STRING */
          entity_key: string;
          /** @sqlType STRING */
          entity_label: string;
          /** @sqlType STRING */
          field_name: string;
          /** @sqlType STRING */
          current_value: string;
          /** @sqlType STRING */
          suggested_fix: string;
          /** @sqlType STRING */
          fix_action: string;
          /** @sqlType STRING */
          fix_payload: string;
          /** @sqlType STRING */
          status: string;
          /** @sqlType STRING */
          resolution_notes: string;
          /** @sqlType TIMESTAMP */
          updated_at: string;
        }>;
      };
    dq_metrics: {
        name: "dq_metrics";
        parameters: {
          /** STRING - use sql.string() */
          _refresh: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          metric_key: string;
          /** @sqlType STRING */
          metric_group: string;
          /** @sqlType STRING */
          metric_label: string;
          /** @sqlType DOUBLE */
          actual_value: number;
          /** @sqlType DOUBLE */
          expected_value: number;
          /** @sqlType STRING */
          unit: string;
          /** @sqlType STRING */
          severity: string;
          /** @sqlType STRING */
          status: string;
          /** @sqlType STRING */
          description: string;
          /** @sqlType TIMESTAMP */
          measured_at: string;
        }>;
      };
    facilities_by_state: {
        name: "facilities_by_state";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          state: string;
          /** @sqlType BIGINT */
          facility_count: number;
        }>;
      };
    facilities_by_type: {
        name: "facilities_by_type";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          facility_type: string;
          /** @sqlType BIGINT */
          facility_count: number;
        }>;
      };
    facility_summary: {
        name: "facility_summary";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          total_facilities: number;
          /** @sqlType BIGINT */
          states_covered: number;
          /** @sqlType BIGINT */
          facility_types: number;
        }>;
      };
    hello_world: {
        name: "hello_world";
        parameters: {
          /** STRING - use sql.string() */
          message: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          value: string;
        }>;
      };
    mapping_facility_specialty: {
        name: "mapping_facility_specialty";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          facility_id: string;
          /** @sqlType STRING */
          facility_name: string;
          /** @sqlType STRING */
          specialty: string;
          /** @sqlType STRING */
          specialty_category: string;
        }>;
      };
    mapping_health_indicator_specialty: {
        name: "mapping_health_indicator_specialty";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          indicator_key: string;
          /** @sqlType STRING */
          specialty_category: string;
        }>;
      };
    mocked_sales: {
        name: "mocked_sales";
        parameters: {
          /** INT - use sql.int() */
          max_month_num: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          month: string;
          /** @sqlType INT */
          month_num: number;
          /** @sqlType INT */
          revenue: number;
          /** @sqlType INT */
          expenses: number;
          /** @sqlType INT */
          customers: number;
        }>;
      };
    scenario_multi_impact: {
        name: "scenario_multi_impact";
        parameters: {
          /** STRING - use sql.string() */
          facilities_json: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          district_name: string;
          /** @sqlType STRING */
          state_ut: string;
          /** @sqlType DOUBLE */
          baseline_hypertension_demand_pct: number;
          /** @sqlType DOUBLE */
          scenario_hypertension_demand_pct: number;
          /** @sqlType DOUBLE */
          baseline_diabetes_demand_pct: number;
          /** @sqlType DOUBLE */
          scenario_diabetes_demand_pct: number;
          /** @sqlType BIGINT */
          baseline_facility_count: number;
          /** @sqlType BIGINT */
          scenario_facility_count: number;
          /** @sqlType BIGINT */
          delta_facility_count: number;
          /** @sqlType BIGINT */
          baseline_cardiac_facility_count: number;
          /** @sqlType BIGINT */
          scenario_cardiac_facility_count: number;
          /** @sqlType BIGINT */
          delta_cardiac_facility_count: number;
          /** @sqlType BIGINT */
          baseline_bed_capacity: number;
          /** @sqlType BIGINT */
          scenario_bed_capacity: number;
          /** @sqlType BIGINT */
          delta_bed_capacity: number;
          /** @sqlType DOUBLE */
          baseline_supply_demand_gap: number;
          /** @sqlType DOUBLE */
          scenario_supply_demand_gap: number;
          /** @sqlType DOUBLE */
          delta_supply_demand_gap: number;
          /** @sqlType DOUBLE */
          nfhs_households_surveyed: number;
        }>;
      };
    specialty_categories: {
        name: "specialty_categories";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          specialty_category: string;
        }>;
      };
    specialty_options: {
        name: "specialty_options";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          specialty: string;
        }>;
      };
  }
}
